### ISSUE TITLE
Server Crashes when using Krypton

### ISSUE THREAD

**Issue by AwesomeAyushx** [CardboardPowered/cardboard#185] opened 2021-03-31 15:02 UTC
With only the latest version of Cardboard, fabric API, and krypton 0.1.2, the server crashes during boot

**Comment by cylian914** [comment] 2021-04-09 08:10
need the log

**Comment by xslingcn** [comment] 2021-04-10 09:25
> need the log

`[17:24:22] [main/INFO]: Loading for game Minecraft 1.16.5
[17:24:22] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
SourceNameRebuildVisitor: Invalid class filename: com/google/gson/internal/$Gson$Types$ParameterizedTypeImpl, please fix!
SourceNameRebuildVisitor: Invalid class filename: com/google/gson/internal/$Gson$Preconditions, please fix!
SourceNameRebuildVisitor: Invalid class filename: com/google/gson/internal/$Gson$Types, please fix!
SourceNameRebuildVisitor: Invalid class filename: com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl, please fix!SourceNameRebuildVisitor: Invalid class filename: com/google/gson/internal/$Gson$Types$WildcardTypeImpl, please fix!
[17:24:30] [ForkJoinPool-1-worker-15/WARN]: Non-Fabric mod JAR at "C:\Users\xsling\Desktop\Fabric_Remake\mods\FastFurnace-1.16.4-4.4.0.jar", ignoring
[17:24:30] [main/INFO]: [FabricLoader] Loading 59 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, hydrogen@0.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.4, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-permissions-api-v0@0.1-SNAPSHOT, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, luckperms@5.3.21, carpet-extra@1.4.30, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, carpet@1.4.31, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-command-api-v1@1.1.1+351679a77d, phosphor@0.7.1+build.11, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, com_github_wearblackallday_javautils@ab1e0ad736be1d2c2d74c68fa8e9e40e752f2d18, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@155, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, rich_chat@1.0.1+1.16.3, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, dimthread@1.2.2, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, krypton@0.1.3-SNAPSHOT, fabric-item-groups-v0@0.2.5+351679a77d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[17:24:30] [main/WARN]: Mod `com_github_wearblackallday_javautils` (ab1e0ad736be1d2c2d74c68fa8e9e40e752f2d18) does not respect SemVer - comparison support is limited.
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
        ... 2 more
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod krypton
        at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:441)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
        at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
        at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:439)
        ... 9 more`

**Comment by schindlershadow** [comment] 2021-05-02 18:37
https://pastebin.com/ijiJezrG

cat latest.log   | grep -i cause                                                                                                                     

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin] from phase [DEFAULT] in config [krypton.mixins.json] FAILED during APPLY                                                                                                                                                                                                                                                   Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3248::onKey$initializeVelocityCipher with priority 1000 cannot inject into net/minecraft/class_3248::method_12642(Lnet/minecraft/class_2917;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerLoginNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin -> Prepare Injections ->  -> handler$zkp000$onKey$initializeVelocityCipher(Lnet/minecraft/class_2917;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]                                              Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered                                                                                                             Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin] from phase [DEFAULT] in config [krypton.mixins.json] FAILED during APPLY     Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3248::onKey$initializeVelocityCipher with priority 1000 cannot inject into net/minecraft/class_3248::method_12642(Lnet/minecraft/class_2917;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerLoginNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin -> Prepare Injections ->  -> handler$zkp000$onKey$initializeVelocityCipher(Lnet/minecraft/class_2917;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]

**Comment by IsaiahPatton** [comment] 2021-08-13 03:17
Should now be fixed in the latest update.

**Closed by IsaiahPatton** 2021-08-13 03:17 UTC
