### ISSUE TITLE
Incombatability with Sodium

### ISSUE THREAD

**Issue by ZenithAstralis** [CardboardPowered/cardboard#169] opened 2021-03-15 02:43 UTC
https://paste.ee/p/eLcOk

Mods Installed:
CardboardMod-1.16.4.jar [build 150 according to MultiMC, but I got it from the [build 153 download page](https://ci.codemc.io/job/IsaiahPatton/job/Cardboard/lastStableBuild/)]
fabric-api-0.32.0+1.16.jar
sodium-fabric-mc1.16.3-0.1.0.jar

Fabric Modloader 11.3
Minecraft 1.16.4
MultiMC Launcher v0.6.11-1430
Java jre1.8.0_281 (x64)
4096MB memory allocated
Windows 10

Took a long while to track down which mods were conflicting to make that one, I started (stupidly) from the All Of Fabric 3 modpack, then added some more, THEN tried troubleshooting lol.
Edit: I'm posting this over at [the Sodium github](https://github.com/CaffeineMC/sodium-fabric/issues/583) as well

**Comment by ZenithAstralis** [comment] 2021-03-15 07:15
Update: When entering a singleplayer world (a new one; creative mode, cheats on, all else default) I get these additional lines:
```
[23:04:16] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:04:26] [main/INFO]: Narrator library for x64 successfully loaded
[23:04:54] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
22:04:54.824 [Server thread] ERROR net.minecraft.server.MinecraftServer - Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1974) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:67) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
22:04:54.827 [Server thread] ERROR net.minecraft.server.MinecraftServer - This crash report has been saved to: H:\Games Stuff\Minecraft & Minecraft Acessories\mmc-stable-win32\MultiMC\instances\1.16.4\.minecraft\crash-reports\crash-2021-03-14_23.04.54-server.txt
22:04:54.828 [Server thread] ERROR net.minecraft.server.MinecraftServer - Exception stopping the server
java.lang.NullPointerException: null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:572) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:599) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:203) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

**Comment by magneticflux-** [comment] 2021-03-15 08:36
It appears the issue is because Cardboard shadows SLF4J (which it shouldn't). This causes class loading issues because SLF4J isn't loaded with JLine3 like it expects because it's force-loaded by being shadowed into Cardboard, which is loaded by the Fabric mod classloader.

As a workaround, use a build of Cardboard before 3cb210952db44b3a5117eb832fae8279c271ba31 maybe? Idk

**Comment by DeZoWaRe** [comment] 2021-03-21 10:51
Sodium client mod

**Comment by IsaiahPatton** [comment] 2021-04-08 11:34
Should be fixed now.

**Closed by IsaiahPatton** 2021-04-08 11:34 UTC
